apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-flask
spec:
  selector:
    matchLabels:
      app: ps-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: ps-flask
      annotations:
        ad.datadoghq.com/tags: '{"app": "ps-flask","role": "backend", "library":"python"}'
    spec:
      containers:
      - name: ps-flask
        image: cahillsf/ps-flask:0.0.1
        ports:
        - containerPort: 8000
        env:
        - name: DEPLOYMENT
          value: "kubernetes"
        - name: RECAPTCHA_SECRET
          value: '6LdvoZIeAAAAAF2zxcW0y1EnCDqK7ZJmpC36h0Pr'
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: DD_AGENT_HOST
          valueFrom:
              fieldRef:
                  fieldPath: status.hostIP
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent